spring.application.name=pilot-td

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when-authorized

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/pilottd}
spring.datasource.username=${DB_USER:pilottd}
spring.datasource.password=${DB_PASSWORD:pilottd}

spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true
